package com.example.temaJar.enumeracion;

public enum Categoria {
    DESARROLLO_DE_SOFTWARE, INFRAESTRUCTURA_Y_REDES, DATA_SCIENCE_ANALYTICS, CIBERSEGURIDAD, DISEÑO_UXUI, SOPORTE_IT, CONSULTORIA_Y_MANAGEMENT;
}
